version: '2'
services:
  postgres:
    image: postgres_test
    network_mode: host
    container_name: postgres_test
    build: ./build_postgres
    ports:
      - "5432:5432"
    env_file:
      - ./env.list
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgres-log:/var/log/postgresql
      - postgres-etc:/etc/postgresql

volumes:
  postgres-etc:
  postgres-log:
  postgres-data:
